spring.application.name=200ok

server.address=0.0.0.0
server.port=5000

# ?? H2 ?? (RDS ??? ?? ???? ????)
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

ai.server.url=http://175.118.225.161:8000
ai.server.use-mock=false