server.port=8080

DB_URL=jdbc:mysql://localhost:3309/app_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
DB_USERNAME=root
DB_PASSWORD=rootpassword
ai.server.url=http://192.168.238.70:8020
KAKAO_REST_API_KEY=c6e3d2b13d3e0ffc31b4d9040ef1fb9b
KAKAO_REST_API_SECRET=iyE86qQIFw3UG2vw03rC7miYdNXlkDAX
JWT_SECRET_KEY=fcCJH1MSDhhJ3pB44VmpHfdyVNCBN6cbc7k+ML8APPc0agPEF6gcQmHRP98XIGrQRlbKC+LhESGugZKRNU6BzA==